services:
  db:
    image: postgres:15-alpine
    container_name: cine-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: cineconnect
    ports:
      - "5432:5432"
    networks:
      - cineconnect-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d cineconnect"]
      interval: 5s
      timeout: 5s
      retries: 5

  cine-db-test:
    image: postgres:15-alpine
    container_name: cine-db-test
    environment:
      POSTGRES_DB: cineconnect_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - cineconnect-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cineconnect_test"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: cine-backend
    ports:
      - "3000:3000"
    env_file:
      - ./apps/backend/.env
    environment:
      DATABASE_URL: postgres://admin:password123@db:5432/cineconnect
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cineconnect-network

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: cine-frontend
    ports:
      - "8080:80"
    env_file:
      - ./apps/frontend/.env
    depends_on:
      backend:
        condition: service_started
    networks:
      - cineconnect-network

networks:
  cineconnect-network:
    driver: bridge