version: '3.8'
services:
  db:
    image: postgres:15
    container_name: cine-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: cineconnect
    ports:
      - "5432:5432"
  frontend:
    build: ./apps/frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
  backend:
    build: ./apps/backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://admin:password123@db:5432/cineconnect
    depends_on:
      - db
