/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AnciennePageRouteImport } from './routes/ancienne-page'
import { Route as IndexRouteImport } from './routes/index'

const AnciennePageRoute = AnciennePageRouteImport.update({
  id: '/ancienne-page',
  path: '/ancienne-page',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ancienne-page': typeof AnciennePageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ancienne-page': typeof AnciennePageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ancienne-page': typeof AnciennePageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ancienne-page'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ancienne-page'
  id: '__root__' | '/' | '/ancienne-page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnciennePageRoute: typeof AnciennePageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ancienne-page': {
      id: '/ancienne-page'
      path: '/ancienne-page'
      fullPath: '/ancienne-page'
      preLoaderRoute: typeof AnciennePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnciennePageRoute: AnciennePageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
