/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as RegisterPageRouteImport } from './routes/RegisterPage'
import { Route as CommunautePageRouteImport } from './routes/CommunautePage'
import { Route as LoginPageRouteImport } from './routes/LoginPage'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MovieMovieIdRouteImport } from './routes/movie.$movieId'

const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunautePageRoute = CommunautePageRouteImport.update({
  id: '/CommunautePage',
  path: '/CommunautePage',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterPageRoute = RegisterPageRouteImport.update({
  id: '/RegisterPage',
  path: '/RegisterPage',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPageRoute = LoginPageRouteImport.update({
  id: '/LoginPage',
  path: '/LoginPage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieMovieIdRoute = MovieMovieIdRouteImport.update({
  id: '/movie/$movieId',
  path: '/movie/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/LoginPage': typeof LoginPageRoute
  '/RegisterPage': typeof RegisterPageRoute
  '/CommunautePage': typeof CommunautePageRoute
  '/favorites': typeof FavoritesRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/LoginPage': typeof LoginPageRoute
  '/RegisterPage': typeof RegisterPageRoute
  '/CommunautePage': typeof CommunautePageRoute
  '/favorites': typeof FavoritesRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/LoginPage': typeof LoginPageRoute
  '/RegisterPage': typeof RegisterPageRoute
  '/CommunautePage': typeof CommunautePageRoute
  '/favorites': typeof FavoritesRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/LoginPage'
    | '/RegisterPage'
    | '/CommunautePage'
    | '/favorites'
    | '/movie/$movieId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/LoginPage'
    | '/RegisterPage'
    | '/CommunautePage'
    | '/favorites'
    | '/movie/$movieId'
  id:
    | '__root__'
    | '/'
    | '/LoginPage'
    | '/RegisterPage'
    | '/CommunautePage'
    | '/favorites'
    | '/movie/$movieId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginPageRoute: typeof LoginPageRoute
  RegisterPageRoute: typeof RegisterPageRoute
  CommunautePageRoute: typeof CommunautePageRoute
  FavoritesRoute: typeof FavoritesRoute
  MovieMovieIdRoute: typeof MovieMovieIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/RegisterPage': {
      id: '/RegisterPage'
      path: '/RegisterPage'
      fullPath: '/RegisterPage'
      preLoaderRoute: typeof RegisterPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/CommunautePage': {
      id: '/CommunautePage'
      path: '/CommunautePage'
      fullPath: '/CommunautePage'
      preLoaderRoute: typeof CommunautePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/LoginPage': {
      id: '/LoginPage'
      path: '/LoginPage'
      fullPath: '/LoginPage'
      preLoaderRoute: typeof LoginPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$movieId': {
      id: '/movie/$movieId'
      path: '/movie/$movieId'
      fullPath: '/movie/$movieId'
      preLoaderRoute: typeof MovieMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginPageRoute: LoginPageRoute,
  RegisterPageRoute: RegisterPageRoute,
  CommunautePageRoute: CommunautePageRoute,
  FavoritesRoute: FavoritesRoute,
  MovieMovieIdRoute: MovieMovieIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
