/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as RegisterPageRouteImport } from './routes/RegisterPage'
import { Route as MovieDetailPageRouteImport } from './routes/MovieDetailPage'
import { Route as LoginPageRouteImport } from './routes/LoginPage'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MovieMovieIdRouteImport } from './routes/movie.$movieId'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterPageRoute = RegisterPageRouteImport.update({
  id: '/RegisterPage',
  path: '/RegisterPage',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieDetailPageRoute = MovieDetailPageRouteImport.update({
  id: '/MovieDetailPage',
  path: '/MovieDetailPage',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPageRoute = LoginPageRouteImport.update({
  id: '/LoginPage',
  path: '/LoginPage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieMovieIdRoute = MovieMovieIdRouteImport.update({
  id: '/movie/$movieId',
  path: '/movie/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/LoginPage': typeof LoginPageRoute
  '/MovieDetailPage': typeof MovieDetailPageRoute
  '/RegisterPage': typeof RegisterPageRoute
  '/favorites': typeof FavoritesRoute
  '/profile': typeof ProfileRoute
  '/watchlist': typeof WatchlistRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/LoginPage': typeof LoginPageRoute
  '/MovieDetailPage': typeof MovieDetailPageRoute
  '/RegisterPage': typeof RegisterPageRoute
  '/favorites': typeof FavoritesRoute
  '/profile': typeof ProfileRoute
  '/watchlist': typeof WatchlistRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/LoginPage': typeof LoginPageRoute
  '/MovieDetailPage': typeof MovieDetailPageRoute
  '/RegisterPage': typeof RegisterPageRoute
  '/favorites': typeof FavoritesRoute
  '/profile': typeof ProfileRoute
  '/watchlist': typeof WatchlistRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/LoginPage'
    | '/MovieDetailPage'
    | '/RegisterPage'
    | '/favorites'
    | '/profile'
    | '/watchlist'
    | '/movie/$movieId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/LoginPage'
    | '/MovieDetailPage'
    | '/RegisterPage'
    | '/favorites'
    | '/profile'
    | '/watchlist'
    | '/movie/$movieId'
  id:
    | '__root__'
    | '/'
    | '/LoginPage'
    | '/MovieDetailPage'
    | '/RegisterPage'
    | '/favorites'
    | '/profile'
    | '/watchlist'
    | '/movie/$movieId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginPageRoute: typeof LoginPageRoute
  MovieDetailPageRoute: typeof MovieDetailPageRoute
  RegisterPageRoute: typeof RegisterPageRoute
  FavoritesRoute: typeof FavoritesRoute
  ProfileRoute: typeof ProfileRoute
  WatchlistRoute: typeof WatchlistRoute
  MovieMovieIdRoute: typeof MovieMovieIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/RegisterPage': {
      id: '/RegisterPage'
      path: '/RegisterPage'
      fullPath: '/RegisterPage'
      preLoaderRoute: typeof RegisterPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/MovieDetailPage': {
      id: '/MovieDetailPage'
      path: '/MovieDetailPage'
      fullPath: '/MovieDetailPage'
      preLoaderRoute: typeof MovieDetailPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/LoginPage': {
      id: '/LoginPage'
      path: '/LoginPage'
      fullPath: '/LoginPage'
      preLoaderRoute: typeof LoginPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$movieId': {
      id: '/movie/$movieId'
      path: '/movie/$movieId'
      fullPath: '/movie/$movieId'
      preLoaderRoute: typeof MovieMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginPageRoute: LoginPageRoute,
  MovieDetailPageRoute: MovieDetailPageRoute,
  RegisterPageRoute: RegisterPageRoute,
  FavoritesRoute: FavoritesRoute,
  ProfileRoute: ProfileRoute,
  WatchlistRoute: WatchlistRoute,
  MovieMovieIdRoute: MovieMovieIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
